name: Notify Dependabot PRs

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"  # Runs daily at 7 AM EST
    
jobs:
  notify-dependabot-prs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Notify Dependabot PRs
      uses: ./.github/actions/dependabot-notifications
      with:
        slack-token: ${{ secrets.SLACK_TOKEN }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        slack-channel: "#dependabot-notifications"
        repositories: |
          [
            "dependabot/dependabot-core",
            "josephabonasara/gitconnect",
            "josephabonasara/QuickApply"
          ]
