name: Notify Dependabot PRs

defaults:
  run:
    working-directory: ./scripts

on:
  workflow_dispatch:  # Allow manual trigger
  schedule:
    - cron: "0 9 * * *"  # Runs daily at 9 AM UTC

jobs:
  notify-dependabot-prs:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Use the public action
    - name: Notify Dependabot PRs
      uses: ./.github/actions/dependabot-notifications/action.yml
      with:
        slack-token: ${{ secrets.SLACK_TOKEN }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        slack-channel: "#dependabot-notifications"
        repositories: |
          [
            "dependabot/dependabot-core",
            "josephabonasara/gitconnect",
            "josephabonasara/QuickApply"
          ]