name: Notify Dependabot PRs

on:
  workflow_dispatch:  # Allow manual trigger
  schedule:
    - cron: "0 9 * * *"  # Runs daily at 9 AM UTC

jobs:
  notify-dependabot-prs:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run the script
    - name: Run Dependabot Notifier
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        REPOSITORIES: |
          [
            "dependabot/dependabot-core",
            "josephabonasara/gitconnect",
            "josephabonasara/QuickApply"
          ]
      run: python scripts/dependabot_notifier.py
